# Generated by Django 4.2 on 2024-02-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_entrega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='apellido',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
