# Generated by Django 4.2 on 2024-02-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_entrega', '0002_alter_estudiantes_email_alter_profesores_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='pre_entrega/images')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m2', models.IntegerField()),
                ('ambientes', models.IntegerField()),
                ('baños', models.IntegerField()),
                ('fotos', models.ManyToManyField(to='pre_entrega.foto')),
            ],
        ),
    ]
