# Generated by Django 4.2 on 2024-02-21 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pre_entrega', '0003_foto_propiedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m2', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='fotos',
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
        migrations.DeleteModel(
            name='Propiedad',
        ),
        migrations.AddField(
            model_name='image',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pre_entrega.property'),
        ),
    ]
